### PR TITLE
fix: use eslint env instead of individual globals

### PR DESCRIPTION
**Pull request by achingbrain**
Setting the value to `false` means it is not writable

### CODE REVIEW

**Comment by hugomrdias** [comment]
maybe its better to set env instead of this https://eslint.org/docs/user-guide/configuring.html#specifying-environments

also for globals (https://eslint.org/docs/user-guide/configuring.html#specifying-globals) it should be `readonly` or `writable`

**Comment by achingbrain** [comment]
I tried that, it thinks `globalThis` is undefined.

**Comment by hugomrdias** [comment]
is Blob and others also undefined or its just globalThis? with env browser ?

**Comment by achingbrain** [comment]
I can make it happy with:

```js
  env: {
    es2020: true,  // for globalThis
    browser: true, // for Blob
    node: true
  },
```

**Comment by achingbrain** [comment]
Setting `es2020: true` might finally solve https://github.com/ipfs/aegir/issues/487 too

**Comment by hugomrdias** [comment]
seems better, what do you think ?

we can remove the globals all together, we already have `/* eslint-env mocha */` in the test files

**Review by hugomrdias — APPROVED** [review]

**Pull request merged**
